### ISSUE TITLE
Week 4 - Hibernate/Dao Exercise Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jcaughlin/ProductivityApp#1]
- [x] The entity in the hibernate config file does not appear to match any of the actual entities. mapping class="edu.matc.entity.User". Is this the latest, working code?
- [ x] Is this the name of your table or the database? https://github.com/jcaughlin/ProductivityApp/blob/65957ca48f37c892a141909b8ebdec0e11fabd4f/src/main/java/edu/matc/entity/Client.java#L10 _Changed name to users_
- [x] dao and unit tests?
- [ X] Is database.properties used for anything? If not delete. deleted
- [x] How are you handling set up/clean up of test data in the database?  You can use a test database by setting up a hibernate config file in the test resources directory. You can also set this up to recreate the test database before running each test class. Refer to the [Hibernate Demo](https://github.com/MadJavaEntFall2017/HibernateDemo) test resource for an example of how do to this.

**Comment by jcaughlin** [comment]
I forgot to check this off and close it out. I have a test db that I clean out. I can't remember the exact, but I know I need to be careful in knowing order doesn't matter in running my tests as one test was deleting a user and then I was searching for the same user in another test.
