### ISSUE TITLE
Code review for Joe

### ISSUE THREAD

**Issue by briandkruse** [jcaughlin/ProductivityApp#4]
# Design/Code Review 2

#### Reviewer Brian Kruse

|Item |Criteria|Rating | Comments/Suggestions|
|--------|---------|---------------|---|
||| Use the following scale:<br> 1= It needs more work<br>  2 = Somewhat<br> 3 = Yes it is great|Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement| 2 |  Bac|
|**Application Functionality**|1. At least 25% of the application's target functionality has been built and is working. </br>2. In comments/suggestions field list and evaluate the functionality that has been implemented.  |2 | There is a nice looking login section. The main Application still needs to be implemented. Authentication still needs work.
|**Unit Tests**|1. Code coverage stats meets or exceeds the developer's code coverage goal. <br> 2. Unit tests are meaningful - they test the business logic and data access aspects of the application (simple methods like getters and setters are not tested) </br> 3. In comments/suggestions field list the code coverage goal and actual current coverage percentage. <br>4. @Before/@BeforeClass/@After/@AfterClass used to reduce redundant code, like creation of entities.<br>5. A test database is used for unit testing and data is cleaned up/reset before or after the tests, so that the tests are re-runnable without developer intervention/cleanup. | 1 | Most unit tests for dao seem to work. Coverage runs at 51% Goal is 100%. There are no tests for non-userdao entities. The tests don't clean up after themselves. Tests assume data from the database.
|**JSPs**|1. Templating is used to eliminate rundandant code(for example, header.jsp, footer.jsp, etc.) <br> 2. CSS or a CSS framework has been implemented to give the site a professional look and feel<br> 3. There is not any embedded java code in the JSPs (EL and JSTL is used appropriately.) |3 |  Templates are well done. Bootstrap is used well. More content is needed but what is there looks excellent |**Code quality**|1. Methods are single-purpose<br> 2. Classes appropriately-sized classes (no monster classes). </br > 3. Methods do not contain many branches or loops that could be simplified or broken up into smaller methods. <br /> 4. The same lines of code are not repeated at all <br> 5. Uses interfaces/super/subclass relationships rather than repeating functionality in multiple classes? For example, using a generic/abstract dao. <br />6. Code does not contain any hard-coded values that should be in a properties file </br> 7. Appropriate logging levels are used. Info, debug, error, etc. </br> 8. There are not any System.out.println() or printStackTrace() statements in the code </br> 9. Package, class, method and variable names are descriptive and meaningful. <br/>10. Include in the comments section what technique you used to evaluate the items above. Using a code quality plug-in is highly recommended as a starting point for code quality reviews. | 3| Joes code passes code quality checks. 
 Methods are small, well written. He doesn't hardcode values. He logs appropriately. I used QA Plug PMS and FindBug to analyze. The errors found were due to hibernate generation or weren't relevant to working code, suggestion: Write more code |
|**Web Service/API integration**|1. Web service/api has been identified in the project problem statement/list of technologies. </br> 2. Web Service integration has been built. <br /> 3. Web Service integration has been unit tested. |2|Open Weather API and Google Calendar. Researched but not documented or implemented|
|**Independent research topic**| 1. Topic has been identified in the project problem statement/list of technologies. </br> 2. Topic research is complete and documented. <br /> 3. Topic has been implemented in the project| 2 | Domain hosting via AWS Route 53, researched but not documented or implemented|  
|**Key takeaways**|List at least 3 things you learned while reviewing this project that will help you in your own project.||Joe does a good job templating, Joe showed me cool features of intellij, Joe showed me how he made his bootstrap css.

**Comment by pawaitemadisoncollege** [comment]
Hi Brian, can you let me know when you finish up the review documentation above so I can check off week 9? Thanks!
